services:
  app:
    build:
      target: prod
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_DEBUG: ${APP_DEBUG:-0}
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${APP_HOST:-app.local}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

  minio:
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${S3_HOST:-s3.local}
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls: internal
      caddy_1: ${MINIO_CONSOLE_HOST:-minio.local}
      caddy_1.reverse_proxy: "{{upstreams 9001}}"
      caddy_1.tls: internal

networks:
  app_proxy:
    external: true
