services:
  app:
    build:
      target: dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./php:/app
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${APP_HOST:-dev.app.local}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

  node:
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    restart: unless-stopped
    working_dir: /app
    command: ["sh", "-c", "tail -f /dev/null"]
    volumes:
      - ./php:/app
    extra_hosts:
      - "${APP_HOST:-dev.app.local}:host-gateway"
    networks:
      - internal_network

  minio:
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${S3_HOST:-dev.s3.local}
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls: internal
      caddy_1: ${MINIO_CONSOLE_HOST:-dev.minio.local}
      caddy_1.reverse_proxy: "{{upstreams 9001}}"
      caddy_1.tls: internal

networks:
  app_proxy:
    external: true
