services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      - CADDY_INGRESS_NETWORKS=app_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  app_proxy:
    external: true
