services:
  app:
    image: ${APP_IMAGE:-app-staging-app}
    build:
      target: staging
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV:-staging}
    networks:
      - caddy_network

  minio:
    networks:
      - internal_network
      - caddy_network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_HOST: ${APP_HOST:-pc4.staging.arukanin.fr}
      S3_HOST: ${S3_HOST:-s3.pc4.staging.arukanin.fr}
      MINIO_CONSOLE_HOST: ${MINIO_CONSOLE_HOST:-minio.pc4.staging.arukanin.fr}
    volumes:
      - type: bind
        source: ./Caddy/Caddyfile.staging
        target: /etc/caddy/Caddyfile
        read_only: true
        bind:
          create_host_path: false
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_network:
    driver: bridge
