services:
  app:
    image: ${APP_IMAGE:-app-staging-app}
    build:
      target: staging
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_RUNTIME_ENV: ${APP_RUNTIME_ENV:-staging}
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${APP_HOST:-staging.app.local}
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

  minio:
    networks:
      - internal_network
      - app_proxy
    labels:
      caddy: ${S3_HOST:-staging.s3.local}
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls: internal
      caddy_1: ${MINIO_CONSOLE_HOST:-staging.minio.local}
      caddy_1.reverse_proxy: "{{upstreams 9001}}"
      caddy_1.tls: internal

networks:
  app_proxy:
    external: true
